import fs from 'node:fs'; import path from 'node:path'; import { parseArgs, forcedLevel } from './args.js'; import { classify } from './classifier.js'; import { findProjectRoot, loadConfig } from './config.js'; import { installProject } from './project-installer.js'; import { runPipeline } from './orchestrator.js'; import { PipelineError } from './errors.js'; import { readStatus, formatStatus, watchStatus } from './status.js';
const VERSION = '1.0.0'; const usage = `Codex Feature Pipeline ${VERSION}\n\nUso:\n  feature "solicitação"\n  feature --dry-run "solicitação"\n  feature --simple|--normal|--complex|--critical "solicitação"\n  feature --plan-only "solicitação"\n  feature --implement-plan <arquivo> ["solicitação"]\n  feature --review-only ["contexto"]\n  feature install-project [--project <pasta>]`;
export async function runCli(argv) {
  const { command, flags: rawFlags, prompt: argumentPrompt } = parseArgs(argv); if (rawFlags.help) return console.log(usage); if (rawFlags.version) return console.log(VERSION); if (rawFlags.installProject) { const result = installProject(rawFlags.project || process.cwd()); console.log(`[feature] projeto configurado: ${result.root}`); return result; }
  const root = findProjectRoot(process.cwd()); if (command === 'status') { const state = readStatus(root); console.log(rawFlags.json ? JSON.stringify(state, null, 2) : formatStatus(state)); return state; } if (command === 'watch') return watchStatus(root);
  const { config, configPath, exists } = loadConfig(root, rawFlags.config); let request = argumentPrompt;
  if (!request && rawFlags['request-file']) request = JSON.parse(fs.readFileSync(path.resolve(root, rawFlags['request-file']), 'utf8')).prompt;
  if (!request && rawFlags['implement-plan']) request = `Implementar o plano ${rawFlags['implement-plan']}`; if (!request && rawFlags['review-only']) request = 'Revisar as alterações atuais.'; if (!request) throw new PipelineError(`Informe uma solicitação.\n${usage}`, 2, 'invalid_arguments');
  const classification = classify(request, forcedLevel(rawFlags)); if (classification.intent !== 'implementation' && !rawFlags['review-only']) { console.log('[feature] solicitação de análise; pipeline não acionado'); return { status: 'not_triggered' }; }
  const flags = { dryRun: !!rawFlags['dry-run'], planOnly: !!rawFlags['plan-only'], implementPlan: rawFlags['implement-plan'], reviewOnly: !!rawFlags['review-only'], approveForMe: !!rawFlags['approve-for-me'] }; const level = classification.level || 'NORMAL'; const phases = phasesFor(level, flags, config);
  if (flags.dryRun) { const output = { projectRoot: root, configPath, configFound: exists, classification: { ...classification, level }, phases }; console.log(JSON.stringify(output, null, 2)); return output; }
  return runPipeline({ request, classification: level, flags, root, config });
}
function phasesFor(level, flags, config) { if (flags.reviewOnly) return [`review ${config.models.reviewer.model}/${config.models.reviewer.reasoning}`]; if (flags.planOnly) return [`plan ${config.models.planner.model}/${config.models.planner.reasoning}`]; if (level === 'TRIVIAL') return [`implement ${config.models.implementer.model}/${config.models.implementer.reasoning}`, 'validate']; const reviewer = level === 'CRITICA' ? config.models.criticalReviewer : config.models.reviewer; return [`plan ${config.models.planner.model}/${config.models.planner.reasoning}`, `implement ${config.models.implementer.model}/${config.models.implementer.reasoning}`, 'validate', `review ${reviewer.model}/${reviewer.reasoning}`, `corrections max ${config.maxCorrectionCycles}`]; }
