import fs from 'node:fs'; import path from 'node:path'; import { runCodexPhase } from './codex.js'; import { captureBaseline, diffFromHead, diffFromTree } from './git-baseline.js'; import { runValidations } from './validation.js'; import { createRun, writeArtifact, writeState } from './state.js'; import { writeReport } from './reporter.js'; import { PipelineError } from './errors.js'; import { assertNoProtectedPaths, filesFromDiff } from './protected-paths.js';
const rank = { TRIVIAL: 0, NORMAL: 1, COMPLEXA: 2, CRITICA: 3 }; const log = (message) => console.log(`[feature] ${message}`);
export async function runPipeline({ request, classification, flags, root, config, phaseRunner = runCodexPhase, validationRunner = runValidations, baselineCapture = captureBaseline, treeDiff = diffFromTree, headDiff = diffFromHead }) {
  const startedAt = Date.now(); const run = createRun(root, request, classification, config); const update = (phase, model = null) => { run.state.phase = phase; if (model) run.state.model = model; else delete run.state.model; writeState(run.root, run.runDir, run.state); }; const codexOptions = { codexCommand: config.codexCommand }; let level = classification; let plan = null; let implementation = null; let review = null; let validations = []; let baseline = null;
  try {
    if (flags.reviewOnly) { const diff = await headDiff(root); writeArtifact(run.runDir, 'review.diff', diff); update('reviewing', config.models.reviewer.model); review = await phaseRunner({ kind: 'review', prompt: reviewPrompt(request, null, diff, []), root, runDir: run.runDir, ...config.models.reviewer, ...codexOptions, sandbox: 'read-only', timeoutMs: config.codexTimeoutMs }); return finish(review.verdict === 'APPROVED' ? 'approved' : 'changes_requested'); }
    if (flags.implementPlan) { plan = { summary: fs.readFileSync(path.resolve(root, flags.implementPlan), 'utf8'), steps: [], acceptanceCriteria: [], risks: [], recommendedLevel: level, escalationReason: '' }; writeArtifact(run.runDir, 'plan.json', plan); }
    else if (level !== 'TRIVIAL') { update('planning', config.models.planner.model); log(`${level} | planejamento: ${config.models.planner.model}/${config.models.planner.reasoning}`); plan = await phaseRunner({ kind: 'plan', prompt: planPrompt(request, level), root, runDir: run.runDir, ...config.models.planner, ...codexOptions, sandbox: 'read-only', timeoutMs: config.codexTimeoutMs }); writeArtifact(run.runDir, 'plan.json', plan); writeArtifact(run.runDir, 'plan.md', renderPlan(plan)); if (rank[plan.recommendedLevel] > rank[level]) level = plan.recommendedLevel; if (flags.planOnly) return finish('planned'); }
    baseline = await baselineCapture(root, run.runDir); update('implementing', config.models.implementer.model); log(`implementação: ${config.models.implementer.model}/${config.models.implementer.reasoning}`); implementation = await phaseRunner({ kind: 'implementation', prompt: implementationPrompt(request, plan), root, runDir: run.runDir, ...config.models.implementer, ...codexOptions, sandbox: 'workspace-write', timeoutMs: config.codexTimeoutMs, approveForMe: flags.approveForMe || config.approveForMe }); assertNoProtectedPaths(implementation.changedFiles, config.protectedPaths); assertNoProtectedPaths(filesFromDiff(await treeDiff(root, baseline.tree)), config.protectedPaths); writeArtifact(run.runDir, 'implementation.json', implementation); update('validating'); validations = await validationRunner(config.validation, root, config.validationTimeoutMs); writeArtifact(run.runDir, 'validations.json', validations);
    if (level === 'TRIVIAL') { if (validations.some((item) => !item.passed)) throw new PipelineError('Validação da tarefa trivial falhou.', 7, 'validation_failure'); return finish('approved'); }
    for (let cycle = 0; cycle <= config.maxCorrectionCycles; cycle += 1) { const diff = await treeDiff(root, baseline.tree); writeArtifact(run.runDir, `review-${String(cycle + 1).padStart(2, '0')}.diff`, diff); const reviewModel = level === 'CRITICA' ? config.models.criticalReviewer : config.models.reviewer; update('reviewing', reviewModel.model); log(`revisão ${cycle + 1}: ${reviewModel.model}/${reviewModel.reasoning}`); review = await phaseRunner({ kind: 'review', prompt: reviewPrompt(request, plan, diff, validations), root, runDir: run.runDir, ...reviewModel, ...codexOptions, sandbox: 'read-only', timeoutMs: config.codexTimeoutMs, attempt: cycle + 1 });
      if (level === 'COMPLEXA' && review.verdict === 'CHANGES_REQUESTED' && review.findings.some((item) => ['high', 'critical'].includes(item.severity))) review = await phaseRunner({ kind: 'review', prompt: reviewPrompt(request, plan, diff, validations), root, runDir: run.runDir, ...config.models.criticalReviewer, ...codexOptions, sandbox: 'read-only', timeoutMs: config.codexTimeoutMs, attempt: cycle + 101 });
      writeArtifact(run.runDir, `review-${String(cycle + 1).padStart(2, '0')}.json`, review); if (review.verdict === 'APPROVED' && validations.every((item) => item.passed)) return finish('approved'); if (cycle === config.maxCorrectionCycles) return finish('changes_requested');
      update('correcting', config.models.implementer.model); run.state.correctionCycles += 1; implementation = await phaseRunner({ kind: 'implementation', prompt: correctionPrompt(request, review, validations), root, runDir: run.runDir, ...config.models.implementer, ...codexOptions, sandbox: 'workspace-write', timeoutMs: config.codexTimeoutMs, approveForMe: flags.approveForMe || config.approveForMe, attempt: cycle + 2 }); assertNoProtectedPaths(implementation.changedFiles, config.protectedPaths); assertNoProtectedPaths(filesFromDiff(await treeDiff(root, baseline.tree)), config.protectedPaths); writeArtifact(run.runDir, `correction-${String(cycle + 1).padStart(2, '0')}.json`, implementation); update('validating'); validations = await validationRunner(config.validation, root, config.validationTimeoutMs); writeArtifact(run.runDir, `validations-${String(cycle + 1).padStart(2, '0')}.json`, validations); }
  } catch (error) { run.state.status = 'failed'; run.state.error = { category: error.category || 'unexpected', message: error.message }; run.state.finishedAt = new Date().toISOString(); writeState(run.root, run.runDir, run.state); error.reportPath = writeReport(run.runDir, { status: 'FAILED', classification: level, correctionCycles: run.state.correctionCycles, durationMs: Date.now() - startedAt, summary: error.message, validations, review }); throw error; }
  function finish(status) { run.state.status = status; run.state.phase = 'complete'; run.state.finishedAt = new Date().toISOString(); writeState(run.root, run.runDir, run.state); const reportPath = writeReport(run.runDir, { status: status.toUpperCase(), classification: level, correctionCycles: run.state.correctionCycles, durationMs: Date.now() - startedAt, summary: implementation?.summary || plan?.summary, validations, review }); log(`${status} | relatório: ${reportPath}`); if (status === 'changes_requested') process.exitCode = 8; return { status, reportPath, runDir: run.runDir }; }
}
const planPrompt = (request, level) => `Atue como arquiteto. Planeje sem editar arquivos. Classificação inicial: ${level}. Solicitação: ${request}`;
const implementationPrompt = (request, plan) => `Implemente integralmente no repositório, respeitando AGENTS.md. Não faça commit, push, deploy, reset ou leitura de segredos. Solicitação: ${request}\nPlano: ${JSON.stringify(plan || {})}`;
const correctionPrompt = (request, review, validations) => `Corrija somente os findings e falhas de validação, rode validações relevantes e não faça commit/push/deploy/reset. Solicitação: ${request}\nRevisão: ${JSON.stringify(review)}\nValidações: ${JSON.stringify(validations)}`;
const reviewPrompt = (request, plan, diff, validations) => `Revise com foco em bugs, regressões, segurança e testes. Não edite arquivos. Solicitação: ${request}\nPlano: ${JSON.stringify(plan || {})}\nValidações: ${JSON.stringify(validations)}\nDiff:\n${diff.slice(0, 180000)}`;
const renderPlan = (plan) => `# Plano\n\n${plan.summary}\n\n${plan.steps.map((step, index) => `${index + 1}. ${step}`).join('\n')}\n\n## Critérios\n\n${plan.acceptanceCriteria.map((item) => `- ${item}`).join('\n')}\n`;
